### ISSUE TITLE
Compatibility issues Meta Quest 2

### ISSUE THREAD

**Issue by korompg** [BastiaanOlij/godot4_openxr_demo#7]
Hi! I'm trying to export this project to a Meta Quest 2 using the latest master build but when I'm trying to run the app I get a multitude of different errors. Are you planning to fix these for the current version or should we wait until the stable beta?

![Screenshot from 2022-08-05 14-24-52](https://user-images.githubusercontent.com/102245985/183077453-f62b965d-81e6-4c6a-ae36-126ac4ceff0b.png)

**Comment by korompg** [comment]
Or should I really just revert to that pull request you've mentioned in the README file?

**Comment by korompg** [comment]
Should I open this as an issue in the official Godot repo? This seems to be a problem with the OpenXR integration itself.

**Comment by korompg** [comment]
If I refactor set_shader_param calls to set_shader_uniform calls, only these are left.

![Screenshot from 2022-08-05 15-12-29](https://user-images.githubusercontent.com/102245985/183085040-edfe9d0d-d65d-4dab-8c41-29b87e5b8d45.png)

**Comment by korompg** [comment]
One less error if I set Project Setting -> Display -> Window -> V-Sync mode to Enabled.

![Screenshot from 2022-08-05 15-20-07](https://user-images.githubusercontent.com/102245985/183086091-f2fb4a7a-8f13-4c37-a2b3-104fa15e5da5.png)

**Comment by korompg** [comment]
The parser errors can be fixed by placing method definitions in PlayerBody.gd above the lines that call them. Now we're left with:

![Screenshot from 2022-08-05 15-35-41](https://user-images.githubusercontent.com/102245985/183089046-e63c1598-8b3b-4847-a2c4-ebd3df02a00a.png)

**Comment by korompg** [comment]
Actually, I only get the user warnings and that user error on my first run after reinstalling. On consecutive launches I only get these listener and unrecognized buffer errors:

![Screenshot from 2022-08-05 15-35-41](https://user-images.githubusercontent.com/102245985/183090795-e0198a21-b755-4dce-acae-1edbc3fb6b0c.png)

**Comment by korompg** [comment]
Okay, I've found that the problem isn't with alpha 13 but with the Android support of OpenXR. Guess I ran into issue #57498.

**Comment by BastiaanOlij** [comment]
@korompg sorry, yes Godot 4 does not yet run on Quest 2 natively.

**Comment by korompg** [comment]
Update: The OpenXR demo now runs on Quest 2 using #64826.

**Comment by BastiaanOlij** [comment]
Super! I need to give that a try this week :)

Are you running with the mobile renderer or the full clustered one?

**Comment by korompg** [comment]
I didn't change that. In the project settings it says Back End.mobile = Forward Mobile.

**Comment by BastiaanOlij** [comment]
Yup, then it should run with the mobile renderer on the quest :)

**Comment by korompg** [comment]
Now that https://github.com/godotengine/godot/pull/65798 has been merged, we can close this issue.

**Comment by BastiaanOlij** [comment]
Thanks for your help on this! excellent result :)
